# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				ravager = true
				bee = true
				axolotl = true
				donkey = true
				cow = true
				chest_minecart = true
				fox = true
				pig = true
				pillager = true
				iron_golem = true
				skeleton = true
				bat = true
				cat = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				player = true
				item = true
				villager = true
				wolf = true
				salmon = true
				tnt_minecart = true
				zombie_villager = true
				furnace_minecart = true
				item_frame = true
				horse = true
				hopper_minecart = true
				vindicator = true
				minecart = true
				painting = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				shark = true
				jellyfish = true
				goose = true
				songbird = true
				eel_freshwater = true
				moose = true
				badger = true
				boar = true
				dragonfly = true
				squirrel = true
				whale = true
				lamprey = true
				horseshoecrab = true
				turkey = true
				coyote = true
				pheasant = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true

			[light_sources.settings.entities.earth]
				carboranea = true
				rubro = true

			[light_sources.settings.entities.whisperwoods]
				moth = true
				wisp = true

			[light_sources.settings.entities.mobz]
				knight2 = true
				armored = true
				toad = true
				fulliron = true
				boar3 = true
				spi = true
				mage2 = true
				katherine = true
				tspider = true
				fast = true
				brownbear = true
				spo = true
				fiora = true
				slimo = true
				skeli2 = true
				knight = true
				skeli4 = true
				dwarf = true
				tank = true
				gchicken = true

			[light_sources.settings.entities.ecologics]
				squirrel = true

			[light_sources.settings.entities.creatures_of_the_snow]
				narwhal = true

			[light_sources.settings.entities.creeperoverhaul]
				dripstone_creeper = true
				cave_creeper = true

			[light_sources.settings.entities.artifacts]
				mimic = true

