# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				donkey = true
				cow = true
				chest_minecart = true
				pig = true
				iron_golem = true
				skeleton = true
				bat = true
				zombie = true
				drowned = true
				sheep = true
				player = true
				item = true
				villager = true
				salmon = true
				tnt_minecart = true
				zombie_villager = true
				furnace_minecart = true
				item_frame = true
				minecart = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true

			[light_sources.settings.entities.betteranimalsplus]
				boar = true
				lamprey = true
				horseshoecrab = true
				goose = true
				songbird = true
				coyote = true
				eel_freshwater = true
				pheasant = true
				crab = true
				badger = true

			[light_sources.settings.entities.artifacts]
				mimic = true

